<?php
/**
 * This file is part of Integento_Styleguide for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Styleguide
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

/* ----------------------------------------------------------
  Breadcrumbs
---------------------------------------------------------- */
?>
<div class="breadcrumbs">
    <ul>
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="home">
            <a itemprop="url" href="#" title="Aller à la page d'accueil">
                <span itemprop="title">Accueil</span>
            </a>
        </li>
        <li itemscope="" itemtype="http://data-vocabulary.org/Breadcrumb" class="cms_page">
            <strong itemprop="title">Styleguide</strong>
        </li>
    </ul>
</div>
<hr />
