<?php
/**
 * This file is part of Integento_Styleguide for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Styleguide
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

/* ----------------------------------------------------------
  Messages
---------------------------------------------------------- */
?>
<h1>Messages</h1>
<ul class="messages">
    <li class="success-msg">
        <ul>
            <li>
                <span>Success message.</span>
            </li>
        </ul>
    </li>
    <li class="error-msg">
        <ul>
            <li>
                <span>Error message.</span>
            </li>
        </ul>
    </li>
    <li class="note-msg">
        <ul>
            <li>
                <span>Note message.</span>
            </li>
        </ul>
    </li>
    <li class="warning-msg">
        <ul>
            <li>
                <span>Warning message.</span>
            </li>
        </ul>
    </li>
</ul>
<hr />
