<?php
/**
 * This file is part of Integento_Styleguide for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Styleguide
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

/* ----------------------------------------------------------
  Pager
---------------------------------------------------------- */
?>
<h1>Pager</h1>
<div class="pager">
    <div class="pages">
        <strong>Page:</strong>
        <ol>
            <li class="current">1</li>
            <li>
                <a href="#2">2</a>
            </li>
            <li>
                <a href="#3">3</a>
            </li>
            <li>
                <a class="next i-next" href="#2" title="Next">
                    <img src="http://placehold.it/30x30" alt="Next" class="v-middle"/>
                </a>
            </li>
        </ol>
    </div>
</div>
<hr />
