<?php
/**
 * This file is part of Integento_Styleguide for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Styleguide
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

/* ----------------------------------------------------------
  Page Title
---------------------------------------------------------- */
?>
<div class="page-title">
    <h1>Page Title</h1>
</div>
<hr />
