<?php
/**
 * This file is part of Integento_Styleguide for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Styleguide
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

/* ----------------------------------------------------------
  Tables
---------------------------------------------------------- */
?>
<h1>Tables</h1>
<h2>Product table</h2>
<p>Cart / Success / Sales</p>
<table class="data-table product-table--base">
    <thead>
        <tr>
            <th>Column name</th>
            <th>Column name</th>
            <th>Column name</th>
        </tr>
    </thead>
    <tbody>
    <?php for ($i = 0; $i < 10; $i++) { ?>
    <tr>
        <td><a href="#" class="product-image"><img src="http://placehold.it/100x100" alt="" /></a></td>
        <td>Cell content</td>
        <td>Cell content</td>
    </tr>
    <?php } ?>
    </tbody>
</table>

<h2>Data table</h2>
<p>Customer Account</p>
<table class="data-table data-table--base">
    <thead>
        <tr>
            <th>Column name</th>
            <th>Column name</th>
            <th>Column name</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Cell content</td>
            <td>Cell content</td>
            <td>Cell content</td>
        </tr>
        <tr>
            <td>Cell content</td>
            <td>Cell content</td>
            <td>Cell content</td>
        </tr>
    </tbody>
</table>
<hr />
