<?php
/**
 * This file is part of Integento_Styleguide for Magento.
 *
 * @license MIT
 * @author Darklg <darklg.blog@gmail.com> <@Darklg>
 * @category Integento
 * @package Integento_Styleguide
 * @copyright Copyright (c) 2016 Integento (http://github.com/InteGento)
 */

/* ----------------------------------------------------------
  Various
---------------------------------------------------------- */
?>
<h1>No results</h1>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<hr />
